version: "3.0"
services:
    # Apache
    apache:
        build:
            context: ./Apache
        ports:
            - 80:80
        volumes:
            - ./Apache/SOLDOUT/soldout:/var/www/html
        